version: "3.8"

services:

  chainlink:
    image: "smartcontract/chainlink:1.7.0-root"
    # restart: always
    command: local n -p /chainlink/secrets/password -a /chainlink/secrets/api
    ports:
      - "127.0.0.1:6688:6688"
    env_file:
      - "chainlink.env"
    links:
      - "db"
    depends_on:
      - "db"
    volumes:
      - /opt/chainlink-node-setup:/chainlink

  db:
    image: "postgres"
    env_file:
      - "secrets/postgres.env"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  chainlink_data:
  db-data:
